# Generated by Django 5.1.4 on 2024-12-05 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=20)),
                ('apellido', models.CharField(blank=True, max_length=20)),
                ('edad', models.IntegerField(blank=True)),
                ('matricula', models.IntegerField()),
                ('materia', models.CharField(max_length=20)),
            ],
        ),
    ]
